# Most of this is copied from Topi - https://github.com/Topis-Lavalink-Plugins/Topis-Source-Managers-Plugin/blob/master/.github/workflows/release.yml

name: Release
on:
  push:
    branches:
      - 'master'

jobs:
    gradle:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: 11

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Execute Gradle build
              run: ./gradlew shadowJar

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: kaogurai-plugin.jar
                path: build/libs/kaogurai-lavalink-plugin-*.jar